# Generated by Django 3.2 on 2021-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditechapp', '0005_schemeseligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='testingApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(max_length=100000)),
            ],
        ),
    ]
