# Generated by Django 3.2 on 2021-04-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20210423_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
