# Generated by Django 3.2 on 2021-04-24 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20210423_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dob', models.DateField(default='', null=True)),
                ('blood', models.TextField(default='', max_length=150, null=True)),
                ('allergy', models.TextField(default='', max_length=150, null=True)),
                ('other', models.TextField(default='', max_length=150, null=True)),
                ('address', models.TextField(default='', max_length=150, null=True)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
