# Generated by Django 3.2 on 2021-04-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditechapp', '0006_testingapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testingApi',
        ),
    ]
